[project]
name    = "my-project"
version = "1.0.0"

# Optional, adding this will enable direct links from the documentation
# to your source code.
git_repo_url = "https://github.com/ConorWilliams/openFLY"

[paths]
compile_commands = "build/compile_commands.json"
