[project]
name    = "openFLY"
version = "0.1.0"

# Enable direct links from the documentation to source code.
git_repo_url = "https://github.com/ConorWilliams/openFLY/blob/main/"

[paths]
compile_commands = "build/compile_commands.json"

[ignore]
ignore_private_members = true
paths                  = ["/tests/", "/src/", "/example/"]

[pages]
homepage = "README.md"
