#pragma once

/**
 * \file version.hpp
 *
 * Defines a set of version macros, generated by CMake
 */

#define FLY_VERSION_MAJOR 0  ///< The major version umber.
#define FLY_VERSION_MINOR 1  ///< The minor version umber.
#define FLY_VERSION_PATCH 0  ///< The patch umber.
