name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test_big_3:
    strategy:
      fail-fast: false
      matrix:
        cpp: [17, 20]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install vcpkg
        uses: friendlyanon/setup-vcpkg@v1
        with: { path: "external/vcpkg", cache-version: "${{ matrix.cpp }}" }

      - name: Configure
        shell: pwsh
        run: cmake "-DCMAKE_CXX_STANDARD=${{ matrix.cpp }}" "--preset=ci-$("${{ matrix.os }}".split("-")[0])"

      - name: Build
        run: cmake --build build --config Release -j 2

      - name: Install
        run: cmake --install build --config Release --prefix prefix

      - name: Test
        working-directory: build
        run: ctest --output-on-failure -C Release -j 2

  test_intel:
    strategy:
      matrix:
        cpp: [17, 20]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install vcpkg
        uses: friendlyanon/setup-vcpkg@v1
        with:
          { path: "external/vcpkg", cache-version: "intel-${{ matrix.cpp }}" }

      - name: Intel Apt repository
        timeout-minutes: 1
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update

      - name: Install Intel oneAPI
        timeout-minutes: 5
        run: sudo apt-get install intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-mpi intel-oneapi-mpi-devel

      - name: Setup Intel oneAPI environment
        run: |
          source /opt/intel/oneapi/setvars.sh
          printenv >> $GITHUB_ENV

      - name: Configure
        shell: pwsh
        run: cmake "-DCMAKE_CXX_STANDARD=${{ matrix.cpp }}" --preset=ci-ubuntu -DCMAKE_CXX_COMPILER=icpx

      - name: Build
        run: cmake --build build --config Release -j 2

      - name: Install
        run: cmake --install build --config Release --prefix prefix

      - name: Test
        working-directory: build
        run: ctest --output-on-failure -C Release -j 2

  docs:
    # Deploy docs only when builds succeed
    needs: [test_big_3, test_intel]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with: { python-version: "3.8" }

      - name: Install python dependancies
        run: pip3 install -r docs/requirements.txt

      - name: Install Doxygen
        run: sudo apt-get update -q
          && sudo apt-get install doxygen -q -y

      - name: Configure
        run: cmake -S ./docs -B build/docs

      - name: Build docs
        run: cmake --build build/docs

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/sphinx
        if: github.repository_owner == 'conorwilliams' && github.event_name == 'push'
